source: dir
destination: dir
safe: true
exclude: dir
include: dir
keep_files: fids
timezone: timezone
encoding: utf8

defaults:
 -
  scope:
   path: "projects"
   type: "pages"
  values:
   layout: "project"
   author: "Mr. Hyde"
   category: "project"